--[[ GENERATED -- do not edit by hand.

     Quests on octowow.st that no published pfQuest database
     carries, built from cached pages by tools/parse_octo.py.
]]

pfQuestOctoExtra = pfQuestOctoExtra or {}
pfQuestOctoExtra.enUS = pfQuestOctoExtra.enUS or {}
local T = pfQuestOctoExtra.enUS
for _, k in ipairs({"quests","units","objects","items"}) do
  T[k] = T[k] or {}
end

T["quests"][41898]={["D"]="These verdant hills were once a friendly place where the Timbermaw and our allies the Blackroot conducted trade, and held great ceremonies.",["O"]="Slay 8 Blackroot Warriors, 8 Blackroot Shaman, 8 Blackroot Ursas, and Grawlsh the Mad for Raghol at the entrance of Timbermaw Hold at the southern end of Moonwhisper Coast.",["T"]="Twisted Relations"}
T["quests"][41899]={["D"]="I am here to give you quest, me big quest giver, me furbolg.",["O"]="Gather 10 Blackroot Totems from the local Blackroot Furbolg for Raghol at the Timbermaw Hold Entrance at southern Moonwhisper Coast.",["T"]="Blackroot Totems"}
T["quests"][41905]={["D"]="While most of the caravans already departed to Stormwind, and eventually to Alah'thalas, there are still many refugees who either wish to aid us here in the Farstrider Lodge or are still preparing for their journey.",["O"]="Recover the robbed provisions from the Dark Iron and bring them to Kelt Thomasin at the Farstrider Lodge.",["T"]="Dark Iron Aggression"}
T["quests"][41906]={["D"]="They are no different than the wild beasts we hunt. The Dark Iron violate the peace of my people by refusing them to find a new home after everything they endured. Not only are they ambushing our caravans to Ironforge, but just recently they began abducting innocents.",["O"]="Free the abducted High Elven family from the Dark Iron camp.",["T"]="No Mercy For The Wicked"}
T["quests"][41907]={["D"]="You there, traveler!",["O"]="Travel north, to Riverhorn Village and recover 7 Riverhorn Heirlooms for Yagoh Riverhorn at his house, south of Riverhorn Village at Moonwhisper Coast.",["T"]="Riverhorn Village"}
T["quests"][41908]={["O"]="Progress",["T"]="Raw Draenethyst Formation"}
T["quests"][41909]={["O"]="Progress",["T"]="Glowing Draenethyst Cluster"}
T["quests"][41910]={["D"]="My tribe sees me in high regard, have we not lived humble but resplendent lives up until just a few moons ago. Now the Moro'gai are sundered, torn apart, leaving us weak and isolated on this island. All the while our fallen brethren are wreaking havoc across the coast, jeapordizing the bonds we had formed with the other inhabitants of this land.",["O"]="Speak with Ar'lia in Moro'gai Village in Moonwhisper Coast.",["T"]="Ar'lia of the Moro'gai"}
T["quests"][41911]={["D"]="We have watched the Fallen Ones' movement closely ever since they had locked us up in our village. While some roam the outskirts along Shimmerstar Lake, the majority of their forces assault us from the north. Sadly, their aggressions are not limited to us. They've begun ambushing the local Tauren and even raided one of their villages, as you may know already. This begs the question: Just what is their goal?",["O"]="Find Nar'an in the outpost north of Moro'gai Village and report back to Ar'lia in Moro'gai Village.",["T"]="Wolf in Sheep's Clothing"}
T["quests"][41912]={["D"]="So this is the crystal you have found on Nar'lan? The item that he paid with his life for? Its surface is crude and surprisingly hot, almost scalding. Even so, there is an air of familiarity about it… Could it be that…?",["O"]="Deliver the red crystal to Riftmaster Ral'pekta in Moro'gai Village.",["T"]="An Ill Omen"}
T["quests"][41913]={["D"]="The mere thought of some… some creature meddling with our sacred draenethyst…! Preposterous, this act cannot go unpunished. Bhu'robi and his Fallen Ones have broken our hallowed traditions and must be held responsible for it. We will find the crystal's foul origin and rid them of this world. Through the art of divination I shall locate from whence it came, but for that I need your assistance. I require specific ingredients and you will bring them to me.",["O"]="Acquire the needed materials and bring them to Riftmaster Ral'pekta in Moro'gai Village.",["T"]="Draenei Divination"}
T["quests"][41914]={["D"]="<Ral'pekta has a stern expression on his face, a bead of sweat runs down his wrinkled olive skin.>",["O"]="Search for the draenei conspirators and bring proof of their death to Ar'lia in Moro'gai village.",["T"]="Hooves and Horns, Clad in Red"}
T["quests"][41915]={["D"]="This new god Bhu'robi talks about in the letter… us draenei have never prayed to any god, but instead worshipped the grandeur of the Draenethyst, symbol of the lifeblood of our homeworld. To even think a draenei would devote itself to a singular entity is bewildering, to put it bluntly.",["O"]="Confront Moro'gai K'la in Moro'gai Village about your newfound insights.",["T"]="Answers from Father"}
T["quests"][41916]={["D"]="The day Bhu'robi left, he and his followers ventured north. The outpost east of Riverhorn Village is still young, meaning they must have settled even further north. <class>, us Draenei are used to settling near bodies of water; even if Bhu'robi forsake our traditions, I am certain he still chose to follow that intuition. In the northern plains of this coast is a shallow lake, it is likely that you will find them there, preaching to their untrue god.",["O"]="Locate Elder Bhu'robi and stop his crusade. Return to Moro'gai K'la once the deed is done.",["T"]="The Elder's End"}
T["quests"][41917]={["D"]="<name> was your name? You earned a place among the Moro'gai. With your aid, we were able to avert a grim fate for our people and have been given the opportunity to once more carve a path for a brighter future. Your arrival must've been preordained by the winds of the Twisting Nether, and for that I am grateful. Thanks to you, my son got the courage to confront me, so that I was able to escape my melancholy. He has grown past the little boy I had known him for.",["O"]="Speak with Ar'lia at the marketplace of Moro'gai Village.",["T"]="A Student's Determination"}
T["quests"][41918]={["D"]="A foreigner? Excuse me, this must sound quite ironic to you, does it not? Is it not me who is alien to your world after all. Nevertheless, am I correct in assuming you are of the travelling sort? That might be most opportune for me. My name is Hara'ne of the Moro'gai. My people settled not far from here on the islands in Shimmerstar Lake. As we speak, renegade members of our own tribe are laying siege to our village, causing many of my kin to suffer grievous injuries. While under blockade, we lack many of the bare necessities, which is why I traveled here. The moths inside Moonsilk Hollow produce powerful silk full of potent energy, with which we can accelerate the healing of our wounded friends.",["O"]="Bring spools of silk from Moonsilk Hollow to Elder Sage Azh'okar in Moro'gai Village.",["T"]="Silken Song"}
T["quests"][41919]={["D"]="What a pleasure to see you again. I take it you have brought Elder the silken spools? Splendid! This may be a good start, but I'm afraid what we gathered so far won't be sufficient for long. To ensure the continued safety of our people, it is necessary for us to create a steady flow of materials for the elder to process. If you could be so kind and gather further silken spools from the moths in Moonsilk Hollow? The Moro'gai will be in your debt, that much is certain.",["O"]="Bring spools of silk from Moonsilk Hollow to Elder Sage Azh'okar in Moro'gai Village.",["T"]="More Silk for the Wounded"}
T["quests"][41920]={["D"]="One tragedy after another! First I had to take a detour due to these wretched Fallen Ones roaming around the woods, and now my cart broke down, leaving me little choice but to repair it here, out in the open. Not to mention the important cargo I had stashed on the cart being lost in the forest to the east.",["O"]="Find Maghan's lost cargo and bring it to P'li in Moro'gai Village.",["T"]="Fallen One Cargo"}
T["quests"][41921]={["D"]="Now that I regained my strength, my senses are sharp once more, and I can feel the magic of your world far better than before. What I felt, however, was surprising, a sensation that had an aura of familiarity to it. It came from the north, a whirlwind of conflicting energy. Ideals clashing, emotions uncertain and a great change abound. You may have seen it already, beyond the cliffs to the north is a land clad in blue, its cerulean hue draping the coast in serene midnight. In my mind I have the image of a great shimmering lake, there I had felt the sensation the strongest.",["O"]="Travel to Moonwhisper Coast north of Azshara and locate the shimmering lake.",["T"]="A Familiar Disturbance"}
T["quests"][41922]={["D"]="I could have never imagined it. For so long we have lived with the thought of us being the only draenei to have survived the breaking of our homeworld. To think that another tribe has managed to escape to your world as well…",["O"]="Bring Elder Krasheen's projection crystal to Sanv K'la in the Harborage in the Swamp of Sorrows.",["T"]="Homecoming"}
T["quests"][41935]={["D"]="The tablet you find emanates with ancient power. Drenched in an imposing aura, you surmise it must be a relic from bygone times that somehow found its way into the clutches of Majordomo Executus. Reading its contents, runes and markings can be found describing a powerful resurrection spell for ageless beings. All that is needed is the recital of its lines and the essence of whatever being you wish to anchor once more into the mortal world.",["O"]="End",["T"]="Rite of Resurrection"}
T["quests"][41936]={["D"]="The crystal humms in an ominous rhythm. Peering through its flawless surface, it's as if a vortex of swirling energies reside inside the gemstone. Icecold to the touch and surprisingly heavy, you can feel a dark and terrifying power beckoning from beyond wherever this endless void is leading. Enthralled and shocked at the same time, you decide to bring it to a powerful warlock who might be able to help you with it.",["O"]="End",["T"]="Twisting Rift Crystal"}
T["quests"][41938]={["D"]="The stone has writings on its surface that you cannot decipher. Perhaps someone from the Earthen Ring proficient in this language can assist you.",["O"]="End",["T"]="Windtorn Crest Stone"}
T["quests"][41939]={["D"]="Apologies, I said I could read a few passages, but even then it is fairly cryptic. It speaks of an order, the order to attack the meddling mortals. You found this on one of the invading air elementals? Greka told me about what had happened while most of our members were gone. It appears this was no mere coincidence, but a coordinated attack utilizing a moment of weakness in our defenses. Further down, it states the following:",["O"]="Banish the elemental figurehead inside Windhorn Canyon and report back to Shovu at the Earthen Ring in the Stonetalon Mountains.",["T"]="Vortalus’ Edict"}
T["quests"][41940]={["D"]="May the spirits be with you, friend. I am Grakk Windtamer, a member of the Earthen Ring. It is our duty to ensure the elemental balance of our world is not disturbed. For that, us shamans of the Earthen Ring go on pilgrimages all across Azeroth to assess said balance. The spirits have led me to the plains of the Arathi Highlands, a land ripe with ancient history of the humans, but also full of primal elemental magic. Turmoil brews beneath the surface and the guardians of the binding circles are restless. In their vigilant guard over this prison, they have lost sight of their true nature - and ravage the sacred sites of the highlands.",["O"]="Bring Grakk Windtamer near the Circle of Outer Binding intact cores from each type of elemental residing at the four binding circles in the Arathi Highlands.",["T"]="Elemental Cores"}
T["quests"][41941]={["D"]="Nature is chaotic, <name>. It follows no rules, no set path, no certain future. Within that chaos, life springs forth, nurtured by the elements. With earth as its sustenance, air as its breath and water as its direction, fire is both its upbringing and downfall. A blaze can be comforting, inviting, even smothering in its gentle embrace of warmth. On the other hand, the boundless flame is relentless, searching endlessly for more and more life to consume into it.",["O"]="Firespeaker Bewali at the Earthen Ring requires you to bring Volcanic Soil from around Fire Plume Ridge in the Un'goro Crater to Rimblat Earthshatter at Light's Hope Chapel in the Eastern Plaguelands.",["T"]="Duality of Flame"}
T["quests"][41942]={["D"]="While many pilgrims returned to the Earthen Ring not long ago, I remained here. To further my research into the Plague of Undeath. Far Seer Earthfury once saw potential for a cure in our Forsaken allies, so I have made it my mission to assist him in ridding them of their rotting curse. Rayne and I already made great strides in healing the dead earth of these lands. She is a remarkable ally, and we are certain we can achieve a breakthrough in our endeavour - in many parts thanks to the soil you brought.",["O"]="Bring Sporeridden Bones and a Twisted Sapling to Rimblat Earthshatter at Light's Hope Chapel in the Eastern Plaguelands.",["T"]="The Plaguewood"}
T["quests"][41943]={["D"]="Not far from here, in the crag desert of Desolace lie the halls of Maraudon. It is said to be the birthplace of the baneful Centaur, a hallowed place for their people and ancestors. These halls have been defiled, twisted into a noxious lair of disease and putridity. Rotting the earth and befouling the water, this sickness has taken deep roots in the cavern system underneath and caused a tremendous amount of pain to the spirits and nature.",["O"]="Cleanse the corruptive waters and its source inside of Maraudon and return to Ohona Riverbend at the Earthen Ring in the Stonetalon Mountains.",["T"]="Foul Waters"}
T["quests"][41944]={["D"]="We are isolated on this island, the Fallen Ones lurking in the thicket of the woods, ready to strike at our unsuspecting hunters. Only the veteran hunters were successful in securing game, while the less experienced returned with griveous wounds. Still, it is not enough. The people starve, as we cannot survive from the little fruit and fish we have.",["O"]="Deliver meat to Cook Rem'sai in Moro'gai Village.",["T"]="The Long Hunt"}
T["quests"][41945]={["D"]="All this riffraff! To think an imbecile like Bhu’robi is the cause for all this chaos. He was always a nuisance, radical ideas and delusional aspirations walked hand in hand with this fool of a man! You would assume our chieftain would have realized this sooner, but he got blinded by his feelings of compassion to his ‘old friend’. Pah, to the nether with it I say. Bhu’robi is no longer a Draenei in my eyes, let alone a Moro’gai.",["O"]="Fena Ma’dar in Moro’gai Village wants Lunarclaw brains to help with her headache.",["T"]="Respect the Elderly"}
T["quests"][41946]={["D"]="Everything is broken! Everything is trampled! These treacherous Fallen Ones keep pillaging the only farm we have, and I am all alone out here. Barely could I escape with my life during the last raid, but with the injury to my leg, I doubt I will be that lucky again. Parash’ka, I fear they might come back again soon and without help, my farm and I will perish at their hands! Please, help me!",["O"]="Defend Farmer Denphar from the pillaging draenei!",["T"]="Farm Raiders"}
T["quests"][41947]={["D"]="Wanted: Tama’an the Ruthless",["O"]="Kill Tama’an the Ruthless and bring his necklace to Chief Defender Hamaam in Moro’gai Village.",["T"]="Wanted: Tama’an the Ruthless"}
T["quests"][41948]={["D"]="Wanted: Growlpaw",["O"]="Return with the paw of Growlpaw and the stolen wares to Chief Defender Hamaam in Moro’gai Village.",["T"]="Wanted: Growlpaw"}
T["quests"][41949]={["D"]="Moro’gai K’la informed me of the developments concerning the fiendish Fallen Ones. Revolting to think they’d ally themselves with these demon-looking beasts against their own kind! Parash’ka, the time for retribution has come. My chieftain may have found his original vigor, but he is still all too forgiving. Fortunately for him and the tribe, I am the cruel hand that he needs. Seek out the demonic Foulheart hiding in these lands and bring me their horns as proof. The Moro’gai will instill fear in their rotten hearts, for their death will be painful.",["O"]="Deliver Foulheart Horns to Chief Defender Hamaam in Moro’gai Village.",["T"]="Horns of their Allies"}
T["quests"][41950]={["D"]="The crate you’ve found on the satyr is heavy and resonates with a droning noise. Opening the lid exposes numerous of the dark red crystals you’ve seen around the grotto, tainted draenethyst shards filled with an unsettling energy. Riftmaster Ral’pekta should see this.",["O"]="Return to Riftmaster Ral’pekta in Moro’gai Village with the crystal crate from Foulheart Sanctum.",["T"]="Parcel to Nowhere"}
T["quests"][41951]={["D"]="Excuse my outburst. I’ve tended to the crystals throughout all of my five hundred and twenty-seven years, my connection to them is deeper than most draenei out there. Nevertheless, there is a most peculiar thing about these crystals. They are packed inside a crate, a situation that appears strange given the fact the tained draenethyst was all around the demonic fiends inside that canyon. Which leads me to believe that these crystals were destined to be delivered somewhere.",["O"]="Talk with Maghan the merchant south of Moro’gai Village about the crystal crate.",["T"]="Merchant’s Knowledge"}
T["quests"][41952]={["D"]="The crates belong to the bearfolk just across the road, the way the wood of the crate is bent is typical for them. When we were still actively trading I inspected the crates regularly, so I am sure it has to be theirs. Trade between us may have stopped now, but there is still activity coming from their fortifications over there. Whenever I traverse these roads, I sometimes get a glimpse of a burly bearfolk going further south and towards that cave up the hill. If you want to get to the bottom of this, your best chance would be to see what they’re carrying.",["O"]="Pursue the Blackroot Runners and bring their cargo to Riftmaster Ral’pekta in Moro’gai Village.",["T"]="Out of the Moonlight"}
T["quests"][41953]={["D"]="Whatever the bearfolk intend on accomplishing with the tainted draenethyst, we cannot let it happen. It shall not be misused for nefarious reasons, and as Draenei, it is our duty to ensure it stays that way.",["O"]="Enter Timbermaw Hold and retrieve the corrupted draenethyst. Bring them to Riftmaster Ral’pekta in Moro’gai Village of Moonwhisper Coast if you are successful.",["T"]="Draenethyst Recovery"}
T["quests"][41954]={["D"]="I have heard a lot about the craftsmen of your world. They bend stone, smelt ores and weave fabric imbued by the moon’s light to create powerful armor and weaponry. Still, they are but a child’s first attempt at crafting when compared to the legacy of Draenei craftsmanship. Centuries of wisdom passed down through generations, guarded by the best of the best in their field.",["O"]="Deliver crafted leather armor to Master Craftsman T’kalpa in Moro’gai Village.",["T"]="Skills of an Unknown World"}
T["quests"][41955]={["D"]="In this world live three-headed beasts called Hydra, creatures you surely have encountered plentiful on your journey. Their hide possesses innate magical quantities; magic we can foster and heighten with our ancient draenei technique. I will share with you on how to craft a powerful set of armor with these hides after you bring me leather from those beasts and the hides of three legendary hydra hiding in your world. Take this note with you. The elders helped me locate them not long ago, but in our current situation I cannot leave the village.",["O"]="Collect Hydra Leather and the three legendary hydra hides. You can gather Hydra Leather by skinning powerful hydra.",["T"]="Tricolored Hide-ra"}
T["quests"][41956]={["D"]="Highlord Bolvar Fordragon commands the armies of Stormwind and drives the Alliance war effort against the Horde. While he holds the throne room, their soldiers march with purpose. This week, break that resolve. End Bolvar and bring me his head.",["O"]="Slay Highlord Bolvar Fordragon in Stormwind Keep and bring his head to Overlord Runthak in Orgrimmar.",["T"]="Bounty: Head of Highlord Bolvar Fordragon"}
T["quests"][41957]={["D"]="Every rifle, blade, and cannon the Alliance turns on us is dwarven-made. Raid Ironforge, kill King Magni Bronzebeard and silence the anvils.",["O"]="Slay King Magni Bronzebeard in Ironforge and bring his head to Overlord Runthak in Orgrimmar.",["T"]="Bounty: Head of King Magni Bronzebeard"}
T["quests"][41958]={["D"]="Arch Druid Fandral Staghelm bends the Cenarion Circle to the Alliance's will, loosing night elf druids and Sentinels to choke our expansion across Kalimdor. Cut him down in Darnassus and bring me his head.",["O"]="Slay Arch Druid Fandral Staghelm in Darnassus and bring his head to Overlord Runthak in Orgrimmar.",["T"]="Bounty: Head of Arch Druid Fandral Staghelm"}
T["quests"][41959]={["D"]="Cairne Bloodhoof, High Chieftain of the tauren, binds the Tauren to the Horde and lends them an honor they have not earned. Without him, that bond frays. This week, bring war to the isolated city of Thunder Bluff and return with the Chieftain's head.",["O"]="Slay Cairne Bloodhoof in Thunder Bluff and bring his head to Justine Demalier in Stormwind.",["T"]="Bounty: Head of Cairne Bloodhoof"}
T["quests"][41960]={["D"]="Thrall, Warchief of the Horde, is the will that drives orc, troll, and tauren against us as one. Sever that will and the Horde will turn on each other. Strike into Orgrimmar, end the Warchief, and return with his head.",["O"]="Slay Thrall in Orgrimmar and bring his head to Justine Demalier in Stormwind.",["T"]="Bounty: Head of Thrall"}
T["quests"][41961]={["D"]="Beneath the Ruins of Lordaeron lies the forsaken Undercity. Lady Sylvanas Windrunner rules from a throne deep in the bowels of this plague ridden city. Execute the Banshee Queen and return with her head.",["O"]="Slay Lady Sylvanas Windrunner in the Undercity and bring her head to Justine Demalier in Stormwind.",["T"]="Bounty: Head of Lady Sylvanas Windrunner"}
T["quests"][41967]={["D"]="Our tribe once sought the safety of Windhorn Canyon for protection against the ravages of Kalimdor. Now that we have been expelled, we are subject to the dangers that lurk all around.",["O"]="Slay 6 Needles Cougars and 8 Pesterhide Hyena for Brolan Windhorn at Sagh's Refuge in Thousand Needles.",["T"]="The Need to Survive"}
T["quests"][41968]={["D"]="You there, I am looking for some assistance in gathering some rare materials here in Moonwhisper Coast. You see, someone with a name as prestigious as my own should differentiate themselves.",["O"]="Gather 3 Tough Moonshade Horns from the local kodo for Bulrok Cloudhoof at Moonhorn Retreat in Moonwhisper Coast.",["T"]="Worthy of Cloudhoof"}
T["quests"][41969]={["D"]="Why hello traveler, I am Erna, and I am responsible for much of the garments of Moonhoof Retreat. More specifically, I have been tasked to create an elaborate set of Raiments for Elder Starstrider, as his current pair are growing considerably in age.",["O"]="Bring 6 Ember Worg Fur from the Ember Worgs of Burning Steppes for Erna at Moonhoof Retreat in Moonwhisper Coast",["T"]="Raiments of Ritual"}
T["quests"][41970]={["D"]="It has been weeks since we have heard word from Moonhoof Village, the flow of celebrators seems to have slowed to a crawl. Our worst fears may have been realized. The very plains of Moonwhisper Coast have become too dangerous even for travel.",["O"]="Investigate the missing caravans on the road between Moonhoof Village and Moonhoof Retreat for any signs of foul play.",["T"]="The Missing Caravans"}
T["quests"][41972]={["D"]="The news of this tragedy must be brought to Moonhoof Village, to prevent others from finding a similar fate. I have prepared a letter which is enclosed with details, and have further instructions to help prepare any others who wish to attend our upcoming ceremonies.",["O"]="Travel to Moonhoof Village and deliver Torgan's Letter to Brave Wildheart.",["T"]="Report to Moonhoof Village"}
T["quests"][41973]={["D"]="Hey you, psst, bud.",["O"]="Find the mercenary named Gordnak for Pumpworker Zalwan located at Moonhoof Retreat, somewhere in northern Moonwhisper Coast and deliver him Zalwan's Request.",["T"]="Contracts in Moonwhisper Coast"}
T["quests"][41974]={["D"]="I came to Moonwhisper Coast in search of some profit. I have a contact who is interested in a somewhat unusual material. For what, I am not certain, and I am not one to ask.",["O"]="Gather a Glimmering Hydra Scale from the creatures along the Whispering Shore for Gordnak at Moonhoof Retreat in Moonwhisper Coast.",["T"]="Glimmering Hydra Scale"}
T["quests"][41975]={["D"]="It is hard to admit, but without Zalwan, and your help, I would still be standing here trying to think of what to do. All that is required is to bring Zalwan his end of the pay. That little goblin has sure earned his end, for once.",["O"]="Bring Zalwan's Cut to Pumpworker Zalwan at Tel Co. Basecamp on Tel'Abim.",["T"]="Zalwan's Cut"}
T["quests"][41976]={["D"]="You there, explorer! Have you heard of the sacred canyon of the tauren, where houses are etched in rock and tunnels delve beneath the earth?",["O"]="Gather 8 Windhorn Relics for Tarwegg Dustbrow within Windhorn Canyon and return to him in Ironforge.",["T"]="In Search of Tauren Relics"}
T["quests"][41977]={["D"]="I spent the majority of my life with the Windhorn Tribe, and came to respect and value their traditions. With the pillaging of Windhorn Canyon by the Grimtotem, I fear that the history and culture of the Windhorn may fall into obscurity.",["O"]="Travel into the Windhorn Canyon and recover 8 Windhorn Relics for Sagh at Sagh's Refuge in Thousand Needles.",["T"]="Relics of the Windhorn Tribe"}
T["quests"][41978]={["D"]="Our sacred home has been destroyed, desecrated, and now occupied by the Grimtotem and their tribe. My people were slaughtered like animals, and left to live out our lives as vagabonds with no place to call home.",["O"]="Slay 20 Blackwind Villagers on behalf of Malgan Windhorn at Sagh's Refuge in Thousand Needles.",["T"]="The Wrath of Malgan"}
T["quests"][41979]={["D"]="My fears have been realized, these messages convey a rather serious intent. Long has there been rumors of the Deathtotem, a cult-like branch of the Grimtotem who consort with dark powers for their own nefarious gain. These letters may be a link to finding the truth.",["O"]="Deliver the Longhorn Missive to Cairne Bloodhoof in Thunderbluff.",["T"]="Rumors of the Deathtotem"}
T["quests"][41980]={["D"]="The Deathtotem, I am sure this is the first time you have heard of them. Their very existance is secretive, and shrouded in mystery. I desire you to speak with Rahauro. He is an adjutant to Magatha Grimtotem.",["O"]="Deliver Cairne's Directive to Rahauro at Elder Rise in Thunderbluff.",["T"]="Uncovering the Rumors"}
T["quests"][41981]={["D"]="<Rahauro takes his time inspecting the letter, an expression of shock covers his features, all before he clears his throat in an attempt to hide his surprise.>",["O"]="Deliver Rahauro's information to Cairne Bloodhoof in Thunderbluff.",["T"]="Information for Cairne"}
T["quests"][41982]={["D"]="It would appear that evil once again knocks at our door, and has threatened the balance of peace between the tribes. I must ask you to destroy this Deathtotem, and bring their evil to an end.",["O"]="Slay Prophet Stormhoof, the leader of the Deathtotem within Windhorn Canyon, and return to Cairne Bloodhoof in Thunderbluff.",["T"]="Destroy the Deathtotem"}
T["quests"][41983]={["D"]="Greetings, freezing stranger! How are your adventures? Do you enjoy your stay in Kaneq’nuun? We may have not much to offer, but what we do have is shared with most heartfelt hospitality. Are you by chance interested in sharing stories, us Tuskarr have many legends and folklore to share. Have you come to Kaneq’nuun to hone your fishing skills, perhaps? Then let me share with you the story of Iqa’quluk, the Moonfish!",["O"]="Impress young Tonlok by catching the great Iqa’quluk in the North Sea. Return with the fish to him in Kaneq’nuun at Icepoint Rock.",["T"]="The Great Iqa’quluk"}
T["quests"][41984]={["D"]="People have called me lazy before, back at home. ‘You’re a bum!’ here, ‘I’ve never seen such a slouch!’ there; hefty accusations, if you ask me. And to that I say: they’re all correct. I haven’t become a master fisher out of luck or a secret hidden talent of mine. No, I was simply bored and had nothin’ better to do. So I fished. And fished. And drank. And fished and drank some more, until 30 years had passed and now you’re standin’ before me. But you know what? I think it’s time for a lil’ vacation once in a while, whaddaya think? For that I’d need some supplies, however, but as Lady Luck appears to be in my favor, you’re already here!",["O"]="Bring Nat Pagle in Dustwallow Marsh the requested items.",["T"]="Restocking for Vacation"}
T["quests"][41985]={["D"]="Kid, I need help! Noggenfogger is planning to throw a grand party at Steamwheedle to celebrate some breakthrough in his alchemistic research or whatever, I don’t really get it myself. What I do get is that he expects me to cook up a twelve course meal for the entirety of Gadgetzan’s populace - in four days! I may have the supplies, but my trusty oven is not made for orders that large. If only my cooker was ready to go…",["O"]="Get the completed cooker from Oglethorbe Obnoticus in Booty Bay and bring it to Dirge Quikcleave in Gadgetzan.",["T"]="Don’t tell the Others"}
T["quests"][41986]={["O"]="Progress",["T"]="Oglethorbe’s Scientific Hunger"}
T["quests"][41987]={["O"]="Progress",["T"]="Core of the Elements"}
T["quests"][41988]={["D"]="My pupil Makya ventured into the gloomy jungle of Feralas in search of a relic the Earthen Ring has been trying to secure for a long time. He located it on the Isle of Dread in the bay bordering the Veiled Sea. The mission is dangerous, and the spirits haven’t answered my questions about Makya’s whereabouts yet. Would you be so kind as to check on his well-being? His intention was to anchor at the northern shore of the island, near elven ruins.",["O"]="Find Makya Hillmoon on the Isle of Dread in Feralas.",["T"]="Dreadful Worries"}
T["quests"][41989]={["D"]="I have followed the trails of an ancient elemental relic, the Idol of Neptulon, all the way to these ruins, only to find them overrun by naga. These slithering fiends aren’t known to be caring or well-intentioned so it is possible they are here for the same reason as we are. My skills in combat are limited and not as strong as I hope they’d be, so I really appreciate your presence here. I believe your strength may be just enough to secure the relic in time before the naga return to their watery home with it. According to my information, it should lie within the cave just past these ruins. Good luck out there, I’ll be here if you need me.",["O"]="Retrieve the Idol of Neptulon for Makya Hillmoon on the Isle of Dread in Feralas.",["T"]="Slithering Snakes"}
T["quests"][41990]={["D"]="I swear he did that on purpose! That slimy little human is nothing more than a bratty runt who knows nothing of true honor. While I’m out here facing these… These horrible specters, he is “gathering information” in the draenei village. As if! All he does is stuff himself with whatever food they have to offer. But I’ll show him, or rather we will show him that we can do this without any issues… probably.",["O"]="Collect Maras’ethil Relics in the ruins of Maras’ethil and return to Olgra just outside the ruins.",["T"]="Phasmophobia"}
T["quests"][41991]={["D"]="Bah, this is taking longer than I expected. I had hoped I would be completed with my den by now, but there have been many holdups. I have been unable to build a stockpile of food, and I am familiar with the gnawing hunger of the hibernation season.",["O"]="Gather 8 Moonwhisper Berrys for Kralt the Forgotten on the north side of Moonwhisper Coast near the shore at his den.",["T"]="Preparation for Hibernation"}
T["quests"][41992]={["D"]="Many things were lost when our people were forced out of the cradle that nurtured us and held our fondest memories. My own sight was taken in the uproar of flames, in my foolish mind, I believed myself far too strong to die that day. And by all means, I was right. Alas, greater things were lost than my sight, one thing in particular that I need returned.",["O"]="Return the Scroll of Lo’sho to Mhulf Nighthorn in Moonhoof Village.",["T"]="Youngest Sibling, Always Last"}
T["quests"][41993]={["D"]="A trial is ahead of me, yet I wonder, is it simply I or the tribe that must face it? With empty eyes, I reach for the starry night, and I can see the Moon turning away from my voice. A steep ravine greets me, as I am forced to gently tap my hooves near its end. Terrified of falling, I must keep going. Otherwise, I cannot carry this responsibility to the end.",["O"]="Kill the Shadewalkers of An’she’s Respite. Return to Elder Moonhoof in Moonhoof Village once you are done.",["T"]="Hiding in the Shade"}
T["quests"][41994]={["D"]="Among the Shadewalkers, there is one with a strong conviction, one who has lost her path, one who has broken the hearts of many. Perhaps it was simply due to her own heart being broken. Alas, motivation does not excuse actions, and hers are heinous. She intends to throw the rest of our ancestors into turmoil for petty vengeance.",["O"]="Kill Matriarch Ohanzee and return to Elder Moonhoof in Moonhoof Village.",["T"]="Shade Mother"}
T["quests"][41995]={["D"]="You stand tall, <name>, even when your actions are those of a mindless monster. Tell me, did you even consider questioning the tasks my father set for you? I suppose not. After all, you are nothing more than a bloodthirsty mongrel here for your own benefit. Your hands are stained with the blood of my people.",["O"]="Kill Baxdi’zha in Riverhorn Village. Return to Moonhoof the Younger in Moonhoof Village once you are done.",["T"]="Mindless Monster"}
T["quests"][41996]={["D"]="Were the politics of the village not enough to have a simple fisher like I restless, it turns out I can no longer even have a good night’s sleep. I am not sure what guided these foul slithering creatures from the depths of the water, but they sure love making themselves known.",["O"]="Silence the Tideblade Mistresses at Nendis Point and return to Fisher Rainstrider, in Moonhoof Village.",["T"]="Siren’s Song"}
T["quests"][41997]={["D"]="Along the coast, to the northwest, close to An’she’s Respite and to the Ancestral Grounds, a few hydras have emerged from the bed of the ocean. They are mighty, terrifying beasts that one should not hunt alone. Well, might not be the case for such a seasoned adventurer like yourself. Which brings me to my point.",["O"]="Hunt the Hydra for their meat and return some of it to Fisher Rainstrider in Moonhoof Village.",["T"]="Taste for Hydra"}
T["quests"][41998]={["D"]="Before I managed to make my way to the Moonhoof Village, I passed through the Moro’gai one. Interesting creatures, the draenei are. They were more than open to discuss formulas, basic alchemy, and herbology. Yet whenever I took an interest in the draenethyst crystals they had, they vehemently dismissed the idea.",["O"]="Bring one Raw Draenethyst Formation to Thobias Shallowgrave in Moonhoof Village.",["T"]="Collecting Draenethyst"}
T["quests"][41999]={["D"]="While most of the tribe prefers to wear the leather we managed to obtain during our hunts for both rations and general goods, some of us prefer something one could call more elegant. As a family, mine has carried the name of the material we have worked with for generations. And it is because of a lack of certain silk that can only be obtained from the moths that you and I are currently having this conversation.",["O"]="Gather Mothsilk Cocoons from the Moonsilk Hollow and return them to Shanni Silkhoof in Moonhoof Village.",["T"]="Before They Hatch"}
T["quests"][42000]={["D"]="The Earthmother has not been kind when it came to the fate of the Highborne. Punished for the actions of their queen, the restless souls roam all around Kalimdor and Moonwhisper is no exception. In what was Maras’ethil several spirits yet remain. Bound to this place with no hope.",["O"]="Free the spirits of Mara’sethil and return to Mhulf Nighthorn in Moonhoof Village.",["T"]="Highborne Burden"}
T["quests"][42001]={["D"]="Moonwhisper is one of the few areas across all Azeroth that has a dedicated place of worship for each of the elementals. They are all marked with a shaman stone just like the one before us. Something seems to upset the balance between the elements, however, since they should not be on such heavy guard.",["O"]="Collect prayer beads from the Blackroot furbolgs and return them to Uz’tuk in Moonhoof Village.",["T"]="What Upsets the Elements?"}
T["quests"][42006]={["D"]="Excuse me, do you have a moment? A colleague of mine from the Explorer’s League went off following a clue on an artifact he had been researching about for a long time now. Normally I would trust him to be reasonable, but he intends to descend Frostmane Hollow, the sanctum of the savage Frost Trolls terrorizing Dun Morogh. Please, could you assemble a group of mercenaries and get that fool of a friend back? You will find the entrance to Frostmane Hollow in the mountains of Dun Morogh, very close to the Ironforge Airfields.",["O"]="Search for Archeologist Evenpike inside Frostmane Hollow in Dun Morogh.",["T"]="Searching for Archaeologist Evenpike"}
T["quests"][42007]={["D"]="Locked tight in the frozen grip of the dwarf’s corpse is the fragment of a pristine piece of metal, on which you can see a language unknown to you engraved into the surface. Seemingly worth his death, you bring it into your possession with the intent to let Caskbelly know about it and his friend’s demise.",["O"]="Return to Brohann Caskbelly in the Dwarven District of Stormwind.",["T"]="The Shattered Disc"}
T["quests"][42008]={["D"]="Ba’la dash, malanore. It has been brought to my attention that the deep caverns of Khaz Modan house a particular breed of snow leopards whose fur boasts a remarkable sheen of white. My lord, Astalor of House Sunsworn, requested a one-of-a-kind mantle for his upcoming dinner party and I intend to combine said white fur with the most pristine brocade cloth I have in my possession.",["O"]="Enter Frostmane Hollow in Dun Morogh and acquire a flawless leopard pelt for Shandlar Thethis in Alah’thalas in the Thalassian Highlands. You can find the entrance to Frostmane Hollow near the Ironforge Airfields.",["T"]="The Finest Pelt"}
T["quests"][42010]={["D"]="Ishnu’daldieb, stranger. How rare to see the living strut around in Maras’ethil. Or is my mind playing tricks on me? Excuse me, years of isolation have dulled my sense of decency. You can refer to me as Keeper N’las, that should suffice for now. You know, meeting you on this fine day might be just the solution to my problems that I was looking for. You see, this is not my primary place to live. While the view is breathtaking, my ghastly neighbours are just too brash for my liking, which is why I live further up northwest, in the mountains of this coast. Sadly my only method of transportation there suddenly went silent, much to my surprise. I can repair it, but the journey would be such a hassle and judging from your attire, you’d be way more fit for the job.",["O"]="Collect Frozen Highborne Vials for Keeper N’las and deliver them to his home on the spire near Maras’ethil in Moonwhisper Coast.",["T"]="Powerless Runestone"}
T["quests"][42011]={["D"]="Before I managed to make my way to the Moonhoof Village, I passed through the Moro’gai one. Interesting creatures, the draenei are. They were more than open to discuss formulas, basic alchemy, and herbology. Yet whenever I took an interest in the draenethyst crystals they had, they vehemently dismissed the idea.",["O"]="Retrieve one Starshard from the Starshard Collectors and return it to Thobias Shallowgrave in Moonhoof Village, Moonwhisper Coast.",["T"]="Collectors of Draenethyst"}
T["quests"][42012]={["D"]="Even this crystal is beyond my knowledge. Frustrating, yet pure bliss. I have learned that I know absolutely nothing, which, in truth, is exactly why I keep doing what I am doing. Perhaps I make little sense. But for one such as I that finds researching items and knowledge that has been unheard of so far brings a certain joy.",["O"]="Deliver Thobias’s Satchel to Heghala in Moro’gai Village, Moonwhisper Coast.",["T"]="Actual Collector of Draenethyst"}
T["quests"][42013]={["D"]="We have travelled far to seek shelter with the Moonhoof Tribe. We have long called each other kin, but I was received coldly. The elder granted the audience of a beggar rather than an old friend. I am not pleased, yet I am in no position to argue.",["O"]="Slay the Druids of the Moth and Disciples of Lo’sho in the Grove of the Moon and return to Nuhlgahn Windhorn in Moonhoof Village, Moonwhisper Coast.",["T"]="The Windhorn Burden"}
T["quests"][42014]={["D"]="So the Windhorn chose a representative, rather than doing my bidding on their own. Clever, not exactly what I expected nor wanted, yet An’she whispers them worthy, for now. Since you have already taken their role and seek to be the pillar of their survival, I will give you your next task.",["O"]="Slay Zandaxxius and the Wretched Sprites in the barrow den under the Grove of the Moon and return to Elder Moonhoof in Moonhoof Village, Moonwhisper Coast.",["T"]="Roots of the Grove"}
T["quests"][42015]={["D"]="The elder refuses to allow me to venture into the Grove of the Moon, yet he sent you, or rather the Windhorn, to “deal” with it. I wonder what illusion he spoke of to you, how the druids there have gone mad due to the influence of Lo’sho. Our elder’s mind grows more wretched by the day. Many see it, many turn a blind eye.",["O"]="Slay Landis Stargazer and return to Dhela in Moonhoof Village, Moonwhisper Coast.",["T"]="Lady Stargazer"}
T["quests"][42016]={["D"]="Our next task awaits. Druids that were slumbering in the barrow den have been disturbed and awoken. The elder insists these druids, incapable of seeing between dream and reality, are far too unpredictable and must be dealt with. He considers them, just like the others before, corrupted by Lo’sho.",["O"]="Slay the Lucid Dream Protectors and Stalkers and return to Nuhlgahn Windhorn in Moonhoof Village, Moonwhisper Coast.",["T"]="In Lucid Dreams"}
T["quests"][42017]={["D"]="I am far beyond displeased to hear that I was refused an audience with the elder of Moonhoof while the Windhorn are currently still speaking to him. Thankfully Nighthorn seems to be smarter than the rotting oaf. I was able to obtain quite the information from this man. His displeasure with the elder is shared by both I and several other tribesmen, it seems.",["O"]="Bring Heart of Ohanzee to Duln Ashtotem in Moonhoof Village, Moonwhisper Coast.",["T"]="Heart Full of Shadows"}
T["quests"][42018]={["D"]="Were I to tell you that even in its physical form, while no longer attached to a body, a heart still holds power you cannot imagine, would you believe me? Perhaps not. This heart is full of spite, resentment, and unfulfilled vengeance. And you are the reason for that. I wonder how that makes you feel.",["O"]="Report to Magatha Grimtotem in Elder Rise, Thunder Bluff, Mulgore.",["T"]="Gifting the Matron"}
T["quests"][42019]={["D"]="The coast is host and home to many creatures, amongst them the most particular being the elekk. They are a rare, almost nomadic creature that would rather be in solitude than packs. That being said, they are not easy to find, nor are they easy to fight. But I confess I am working on a weapon that requires one of their mighty tusks.",["O"]="Bring an Elekk Tusk to Ulf Stonetotem in Moonhoof Village, Moonwhisper Coast.",["T"]="The Mighty Elekk"}
T["quests"][42020]={["D"]="A fine spear indeed. I am more than proud of it. I have put all my love, sweat, and passion into forging this weapon. It is the weapon my brother will carry in his battles once his training is done. This, this was my duty as his elder: to provide the means to face his ambition, and, truthfully, to face mine.",["O"]="Deliver the spear to Hulfnar Stonetotem in Bloodhoof Village, Mulgore.",["T"]="Brother’s Duty"}
T["quests"][42037]={["D"]="Blasted Frostmane! Things have been going so well until last week, those blasted trolls came and snuck in during the night. They raided our supplies, and got away with some of our most vital goods.",["O"]="Recovery 6 Airfield Supplies for Supply Officer Mortimus at the Ironforge Airfield in Dun Morogh.",["T"]="Airfield Supplies"}
T["quests"][42038]={["D"]="You there <class>, I have need of your assistance.",["O"]="Slay 8 Frostmane Scouts, 6 Frostmane Drudges, and 6 Frostmane Mystics for Mountaineer Granitebeard at the Ironforge Airfield in Dun Morogh.",["T"]="The Frostmane War"}
T["quests"][42039]={["D"]="My scouts have confirmed the location of a cave to the south west. It is called Frostmane Hollow, some de-facto capital for all of the troll kind in Dun Morogh. If we want to ever put a halt to this threat, we will need to root it out, from deep inside. Rumor has it that their leader is one called Battlemaster Ubukaz, some revered Frostmane fighter who now calls his warriors to battle. I want you to find him, and bring justice for Ironforge.",["O"]="Slay Battlemaster Ubukaz deep within Frostmane Hollow for Mountaineer Granitebeard at the Ironforge Airfield in Dun Morogh.",["T"]="Chieftain Ubukaz"}
T["quests"][42040]={["D"]="<Ranix lets out a breathe of relief, sweat drips down his forehead.>",["O"]="Recover the Tablet of Kaz'gan for Ranix Crackbolt within Frostmane Hollow.",["T"]="A Grave Misunderstanding!"}
T["quests"][42041]={["D"]="Listen here, bucko. I hate admittin’ it, but we’re deep in the mud here. Those crazies over in Kurzen camp thought raidin’ that Alliance camp up the mountains ain’t enough and decided to pay us folks a visit as well. Bad enough that we have our hands full with crocs, tigers, panthers, raptors and trolls - no, these loonies are now on our backs as well. Luckily we could fend them off pretty easily, but they made off with plenty of our supplies and gear.",["O"]="Help out Rufus Hardwick at Nesingwary’s Camp in Stranglethorn Vale by providing some survival supplies.",["T"]="To Survive in the Jungle"}
T["quests"][42042]={["D"]="Our brothers and sisters of the Grove of the Moon have begun treading a misguided path towards destruction. They have abandoned Cenarius' teachings, desecrated his enclaves and endangered countless other peaceful druids. As a warden of nature, I cannot let this transgression pass.",["O"]="Stop the misguided druids on Tyrandas and return to Keeper Bandalar in the Grove of the Sun on Tyrandas afterwards.",["T"]="Led Astray"}
T["quests"][42043]={["D"]="The city above us had been laying silent for millennia, an unspoken oath by all Kaldorei and druids to not enter the forlorn ruins of the Sisterhood. Thus, we had not secured the numerous relics inside for safekeeping, but let them rest in the embrace of time instead. However, now that the deranged defectors have begun trangressing and pillaging the temple, we cannot look idly by any longer. Gather allies and fight your way through their defenses. Retrieve as many artifacts as you can and bring them here to the grove.",["O"]="Collect Elunaris Relics for Grovetender Sellais in the Grove of the Sun on Tyrandas.",["T"]="Belated Preservation"}
T["quests"][42044]={["D"]="<name>, I have received an urgent message from one of the Circle's druidic enclaves in Moonwhisper Coast. Tragedy has befallen our brethren and they seek immediate aid. Please, seek out their grove on the island of Tyrandas in the northeast of Moonwhisper Coast and report to Grovetender Sellais.",["O"]="Speak to Grovetender Sellais in the Grove of the Sun on Tyrandas in Moonwhisper Coast.",["T"]="A Plea for Help"}
T["quests"][42046]={["D"]="I hope you feel welcomed in my home, traveler. You may freely use it for the time being, as I am soon to set my hoofsteps toward Moonhoof Retreat. A ritual of worship is soon to begin, and I, like many, wish to attend.",["O"]="Bring 7 Stagwing Feathers to Luhal Tannedhorn, in his home, just outside Moonhoof Retreat, Moonwhisper Coast.",["T"]="Ritual Ready"}
T["quests"][42047]={["D"]="I have felt somber energies coming from An’she’s Respite of late. While it seems to have not affected the dead there, it has certainly had an effect on the Ancestral Grounds.",["O"]="Slay ten Disturbed Ancestors and return to Groundstender Rainhorn in her hut, at the Ancestral Grounds, Moonwhisper Coast.",["T"]="Back to Sleep"}
T["quests"][42048]={["D"]="That utter knucklehead of a chieftain has sent me all alone to watch over our Ancestral Grounds. He is terribly, terribly wrong for doing so, and I wish he would know that. You are on your way back to Moonhoof Village, aren’t you? Good.",["O"]="Report Rainhorn’s frustration to Elder Moonhoof in Moonhoof Village, Moonwhisper Cove.",["T"]="Rainhorn’s Frustration"}
T["quests"][42049]={["D"]="It seems I am dabbling in forces not even I can begin to imagine. What, not one for humor? Alas, I am unable to cleanse these beads. It’s clear that whatever manner of creature is influencing the furbolgs has ensured that not just anyone can dissipate it. And if I am having so much trouble with merely their possessions, I cannot begin to fathom what it would take to ease the minds of the already corrupted furbolgs.",["O"]="Seek aid from Duke Hydraxis on his lone island in Azshara.",["T"]="In Need of Water"}
T["quests"][42050]={["D"]="The Earthen Ring is a valued mortal friend of the Hydraxian Waterlords. Place those beads beneath one of my binding bracers and let my flowing waters do the rest. I share the concern of your troll friend; the corruption within them is indeed potent. Fret not, it is not potent enough to bring an elemental Duke such as I to his knees, though it has surely done a number on the furbolgs.",["O"]="Return to Uz’tuk with the cleansed Bundle of Beads in Moonhoof Village, Moonwhisper Coast.",["T"]="In Water, Clarity"}
T["quests"][42051]={["D"]="The elements remain in turmoil. With the beads now cleansed by the Duke, we can soothe them. Moonwhisper Cove holds three elemental shrines. You will find one south of here, just before the Grove of the Moon, and the other two by following the road north to An’she’s Respite. Each shrine hosts a shaman stone, just like the one behind me.",["O"]="Use the Bundle of Beads at each Elemental Shrine and then return to Lotka Muddoll in Moonhoof Village, Moonwhisper Coast.",["T"]="Bound in Stone"}
T["quests"][42052]={["D"]="A flame burns bright amid the surrounding darkness within your eyes. That flame speaks for itself. You are no amateur. Bluntly speaking, you are soon to reach your prime as an adventurer and explorer of this world. Mm, yes, you will do.",["O"]="Slay Cerulean Astronomers, Captains and Icewears and return to Gor’dush Jawtaker in the Ancestral Grounds, Moonwhisper Coast.",["T"]="In Blue Defiance"}
T["quests"][42053]={["D"]="I have mentioned a path of glory before. On Draenor, while my kind grew ill with bloodlust and the greed of collecting skulls, we called the road that led to this world a path of glory. What misguided fools we were.",["O"]="Bring Gor’dush Jawtaker the jaws of Starcaller and Spellstriker, in the Ancestral Grounds, Moonwhisper Coast.",["T"]="Jawtaker"}
T["quests"][42055]={["D"]="I have shared with you all the teachings I am able to, which means you have already exceeded my expectations. When you are ready to leave the Red Cloud Mesa, seek my elder brother, Pargan Starstrider, in Bloodhoof Village. He will teach you more of our worship and its history. Yet as your first master, I must also share what knowledge I have gathered in my own devotion.",["O"]="Seek Pargan Starstrider in Bloodhoof Village, Mulgore.",["T"]="In Favor of the Three Siblings"}
T["quests"][42056]={["D"]="Let us put your teachings to the test. South of this tent, past the circle of totems where our warriors train and beneath the shadows and foliage of trees you will find Brave Greenhorn. He looms, wounded, keeping guard over the Winterhoof Water Well which has been run over by the Venture Co.",["O"]="Find Brave Greenhorn and heal his wounds using Lesser Heal (Rank 2). Afterwards, grant him Power Word: Fortitude and then return to Pargan Starstrider in Bloodhoof Village, Mulgore.",["T"]="Garments of the Three Siblings"}
T["quests"][42057]={["D"]="You are here. Ready to start?",["O"]="Progress",["T"]="Light of An'she"}
T["quests"][42058]={["D"]="Your journey has been adventurous so far. A wonderful thing to behold. But now you need to return to Thunder Bluff. Artahla Starstrider wishes to see you, to further the teachings of the Celestial Siblings. She awaits on the Spirit Rise in Thunder Bluff.",["O"]="Speak to Artahla Starstrider in Thunder Bluff.",["T"]="Light of An'she"}
T["quests"][42059]={["D"]="You are here. Ready to start?",["O"]="Progress",["T"]="Spiritwalk"}
T["quests"][42060]={["D"]="The wisdom of your travels can be seen clearly. I think it is time to speak with Artahla Starstrider once more and dive deeper into the lore of your people. She will be able to teach you new spells to help you on your quest. Meet her on the Spirit Rise in Thunder Bluff.",["O"]="Speak to Artahla Starstrider in Thunder Bluff.",["T"]="Spiritwalk"}
T["quests"][42061]={["D"]="Ah. An adventurer.",["O"]="Find what remains of Andanil’s expedition on Moonwhisper Coast.",["T"]="Sunsworn Expedition"}
T["quests"][42062]={["D"]="We are the Sentinels. We swore an oath to protect the lands of Kalimdor. Distance does not weaken that duty, and time does not erase it.",["O"]="Travel to Narvalis Point on Moonwhisper Coast and offer your services to Sentinel Commander Silverstreak",["T"]="Endless Vigil"}
T["quests"][42063]={["D"]="Greetings. Are you traveling to the Moonwhisper Coast?",["O"]="Deliver the Asharan Provisions to Irea Dawncaller in Narvalis Point on Moonwhisper Coast.",["T"]="Delivery from Talendris"}
T["quests"][42064]={["D"]="As a captain of the guard, keeping the expedition alive is my charge.",["O"]="Recover the stolen expedition supplies from the Blackroot furbolgs for Rhys Dawnbreeze in Sunsworn Camp on Moonwhisper Coast.",["T"]="Blackroot Hold"}
T["quests"][42065]={["D"]="The draenei.",["O"]="Bring 40 Fallen One Heads to Rhys Dawnbreeze in Sunsworn Camp on Moonwhisper Coast.",["T"]="Falling the Fallen"}
T["quests"][42066]={["D"]="Those fools think draenethyst crystals are our salvation.",["O"]="Find four valuable magical artifacts in Maras’ethil, then return to Tesania Shadewind in Sunsworn Camp on Moonwhisper Coast.",["T"]="Ghosts of Maras’ethil"}
T["quests"][42067]={["D"]="Before the… incident, we managed to secure a fair number of draenethyst crystals. They are potent, yes, and full of promise. Still, something is missing. I can feel it.",["O"]="Retrieve the Meteor Shard for Arcanist Cerulon in Sunsworn Camp on Moonwhisper Coast.",["T"]="Heaven Falling Down"}
T["quests"][42068]={["D"]="Apologies for the sorry state of our camp. These lands are strange, and their inhabitants even stranger. And… we have suffered a major setback.",["O"]="Listen to what Andanil Sunsworn has to say about the expedition.",["T"]="Expedition Gone Wrong"}
T["quests"][42069]={["D"]="I cannot spare any of my people. They are scholars, arcanists, minds trained for study, not slaughter. I need them lucid, focused, working. If I send them into that den, I lose more than soldiers. I lose what little progress we have left.",["O"]="Find what caused the expedition to wither in the Barrow Den north of Sunsworn Camp, then return with your findings to Andanil Sunsworn in Sunsworn Camp on Moonwhisper Coast.",["T"]="The Withered Den"}
T["quests"][42070]={["D"]="I believe the time has come to face my father and question his judgment. Yet I doubt he would listen; he would, as always, dismiss it as if all he does is for the well of his people and I, his family. I require you to do something for me. I must have the Horde act on my behalf, but not just any adventurer, someone who will have an impact.",["O"]="Seek the aid of Baine Bloodhoof in Bloodhoof Village, Mulgore.",["T"]="One Heir to Another"}
T["quests"][42071]={["D"]="My father was skeptical enough when we received news of an agreement between the Bloodhoof and the Moonhoof, truth be told. The Moonhoof have always favored their independence and, above all, their relationship with the night elves. The Moonhoof were under the umbrella of the Cenarion Circle.",["O"]="Report to Cairne Bloodhoof in Elders’ Rise, Thunder Bluff, Mulgore.",["T"]="Father Will Listen"}
T["quests"][42072]={["D"]="Riverhorn, the Grove of the Moon, An’she’s Respite lost. The elementals rose and wreaked havoc. Dragons, wildlife, naga, furbolgs, and draenei. Atop it all, members of the tribe who chose to leave and seek their own justice were ordered to be slain by the one meant to protect them, and by your hand no less.",["O"]="Return to the younger Moonhoof in Moonhoof Village, Moonwhisper Coast.",["T"]="Bloodhoof Stands with Moonhoof"}
T["quests"][42073]={["D"]="Prepare yourself for the most stubborn bull you have ever met. Whatever you do, do not let go. Insist until he cracks. He will be a terrible opponent of wills, but you must push his buttons enough to have him tell you what he knows and to finally accept his mistakes for what they are.",["O"]="Face the Elder Moonhoof and then speak to him in Moonhoof Village, Moonwhisper Coast.",["T"]="Facing the Elder"}
T["quests"][42074]={["D"]="I have told you my truth. It is up to you now to decide whether you trust it or not. To understand what led Mothshroud to Maras’ethil you must follow in his hoofsteps. My patron points the way. You must travel south, past the Ruins of Nendis and through Moro’gai Village. Once you pass the first bridge that marks the outskirts of the Moro’gai Village, take a left and head east. Just past the lone farmer’s land you will find another bridge.",["O"]="Find clues of the Mothshroud’s ambition in Maras’ethil and return to the Younger Moonhoof in Moonhoof Village, Moonwhisper Coast.",["T"]="Seeking the Truth"}
T["quests"][42075]={["D"]="You have found the letter addressed to me, you know now he aims to take vengeance on the Moonhoof tribe, what else do you require of me, even? What can I or should I tell you that you do not already know? You could not possibly ask me to betray my own master. But you are, that is your goal. To have me tell you in detail what he intends to do, whether his mind is own still or this is a simple meddling of demonic forces seeking to corrupt.",["O"]="Slay Rampaging Grells and Withered Gardeners in the Withered Enclave on the isle of Tyrandas, and return to Ireth Moondancer in the Ruins of Nendis, Moonwhisper Coast.",["T"]="Price of Betrayal"}
T["quests"][42076]={["D"]="Mothshroud is draining the power of the druids and every other living creature under his command to fulfill his ambition. My lost brothers and sisters became twisted, disturbed even as they either willingly or not have remained to serve our former Arch Druid. He was once my master, and I still hold much respect for the man he once was. I did not think I would have to lose two Arch Druids close to my heart to the pain of mourning. Perhaps I was too blind to see it, but he reminds me of Fandral Staghelm.",["O"]="Retrieve Moonlit Charms from the fallen druids of Elun’aran and bring them back to Ireth Moondancer in the Ruins of Nendis, Moonwhisper Coast.",["T"]="Return to the Dream"}
T["quests"][42077]={["D"]="Mothshroud believes that An’she is the one to make Mu’sha shine, through his light. And as such, to punish the patron of Moonhoof that denied his revenge he would take away what he too had lost. It is his ambition to inquire for the aid of the youngest sibling, to punish An’she by making the patron of the day feel loss, so that he would understand what it is to mourn.",["O"]="Kill Arch Druid Mothshroud atop the Temple of Elunaris, Tyrandas and return to the Younger Moonhoof in Moonhoof Village, Moonwhisper Coast.",["T"]="Mothshroud Falls"}
T["quests"][42078]={["D"]="What Mothshroud did was wrong, he bathed himself in the blood of others for his own conviction, his own ambition, his own pain. Are they not similiar? Father chose to remove the problem, to erase it. And in doing so he has sealed his fate.",["O"]="Report to Elder Moonhoof in Moonhoof Village, Moonwhisper Coast.",["T"]="Moonhoof Rests"}
T["quests"][42079]={["D"]="While the scroll appears to be intact there is a seal on it you are not able to unlock. Your thoughts send you towards Mhulf Nighthorn, a worshipper just like you from the Moonhoof Village. Either by your intuition alone or a sign from the Celestial Siblings your hoof guides you toward him, knowing that he may be able to uncover this seal.",["O"]="Take the Half-Burnt Journal to Mhulf Nightorn in Moonhoof Village, Moonwhisper Coast.",["T"]="Secrets of Moonwhisper"}
T["quests"][42080]={["D"]="Father mentioned Ireth Moondancer to you, didn’t he? It seems he might be alive. If this letter is to be believed he was sent to the ruins of Nendis to retrieve something, but failed to meet with Mothshroud in the required time. Seeing as the letter was still there we can safely assume he never made it to the meeting point regardless. Whether those are good or bad we will know in time.",["O"]="Find Ireth Moondancer in the Ruins of Nendins, Moonwhisper Coast.",["T"]="Moondancer Lives?"}
T["quests"][42081]={["D"]="You there, young one! It would appear you have arrived at an opportune time. We have been looking for... A bit of assistance. Many have begun to travel here to Moonhoof Retreat in anticipation for the coming festival, and yet there are still things to be done.",["O"]="Introduce yourself to Elder Starstrider atop of the hill overlooking Moonhoof Retreat and offer your assistance.",["T"]="An Opportune Arrival"}
T["quests"][42082]={["D"]="There are still tasks that need to be completed for the festival to begin, and for this I will need some diligent hands. First I need to fashion a headdress made from the feathers of local creatures. They can be found all across Moonwhisper Coast.",["O"]="Gather 6 Azureshimmer Feathers from the local Hippogryphs and 6 Moonstrider Feathers from the local Plainstriders for Elder Starstrider atop of the hill overlooking Moonhoof Retreat in Moonwhisper Coast.",["T"]="Starstrider Headdress"}
T["quests"][42083]={["D"]="If we are to ever commence the celebration, we must recover an artifact. Near a full month ago, the Fallen One raided our camp and made off with a few possessions, one being our coveted artifact. The Rod of Preservation has been sacred to this celebration, and is required to bring our ancestors into manifestation.",["O"]="Recover the Rod of Preservation from the local Fallen One Draenei for Elder Starstrider atop of the hill overlooking Moonhoof Retreat in Moonwhisper Coast.",["T"]="The Rod of Preservation"}
T["quests"][42084]={["D"]="To finalize our preparations we must now face our final task. To prepare the visage of our elder ancestors we must acquire a rare and enchanted material. In translation, it is known as Dragon Dust, the speckling, magical powder that can be found on the Blue Dragonkin and their ilk who have been blessed by powerful sorcery.",["O"]="Gather 3 Dragon Dust from the Blue Dragonflight present in Moonwhisper Coast for Elder Starstrider atop of the hill overlooking Moonhoof Retreat in Moonwhisper Coast.",["T"]="A Tale of Scales"}
T["quests"][42085]={["D"]="Everything has been prepared, and I am certain the tribe is ready for the festival. It is time to bask in the wisdom of our ancestors, and behold their words. Once I have begun, I should not be disturbed. Speak to me when the celebration has come to conclusion.",["O"]="Behold the Moonhoof Celebration atop of the hill overlooking Moonhoof Retreat in Moonwhisper Coast.",["T"]="The Moonhoof Celebration"}
T["quests"][42086]={["D"]="Nendis.",["O"]="Recover 30 Nendis Mementos from the ruins of Nendis and return them to Talanis Amberscribe in Narvalis Point on Moonwhisper Coast.",["T"]="Echoes of Nendis"}
T["quests"][42087]={["D"]="You have done well recovering those relics from Nendis. More than I hoped for, if I am honest. But there is another place nearby whose story troubles me far more.",["O"]="Find the source of power within the Temple of Elunaris on the Isle of Tyrandas and return it to Talanis Amberscribe in Narvalis Point on Moonwhisper Coast.",["T"]="The Light of Elunaris"}
T["quests"][42088]={["D"]="The tauren of these lands have never been our enemies.",["O"]="Slay 12 Shadewalker Bonerattlers, 8 Shadewalker Brutes and 8 Shadewalker Sharpshooters at An’she’s Respite, then return to Sentinel Commander Silverstreak at Narvalis Point.",["T"]="An’she’s Respite"}
T["quests"][42089]={["D"]="The naga have infested the ruins of Nendis like parasites. Once it was a quiet settlement of our people. Now the streets are flooded with serpents loyal to the Betrayer. Their warriors call themselves the Tideblade. Veterans of the army Illidan unleashed when he first struck these shores.",["O"]="Bring 30 Tideblade Scales to Sentinel Commander Silverstreak at Narvalis Point.",["T"]="Scales of the Tideblade"}
T["quests"][42090]={["D"]="You have proven the naga can bleed. Now we make certain they cannot recover. Two commanders direct the Tideblade forces occupying Nendis. Veterans from the day Illidan’s armies burned the town to the ground.",["O"]="Slay Lady Serpentia and Lord Ta’jax in the ruins of Nendis, then return to Sentinel Commander Silverstreak at Narvalis Point.",["T"]="Serpents Without Heads"}
T["quests"][42091]={["D"]="Narvalis Point stands secure, thanks in no small part to your actions.",["O"]="Bring news of the victory at Nendis to Tyrande Whisperwind.",["T"]="Word to the High Priestess"}
T["quests"][42092]={["D"]="You have seen the crater to the west, yes? The one they call the Starshard Cradle.",["O"]="Slay Starcaller at the Starshard Cradle, then return to Zarazar on Moonwhisper Coast.",["T"]="A Star That Calls Back"}
T["quests"][42093]={["D"]="Narvalis Point may look quiet, but quiet places still need defenders. Sentinels patrol these woods day and night. Most people see their glaives and forget the other half of their craft.",["O"]="Bring 12 Azureshimmer Hippogryph Feathers to Elendon Truebough at Narvalis Point on Moonwhisper Coast. You can find them scattered throughout Moonwhisper Coast.",["T"]="Feathers on Point"}
T["quests"][42094]={["D"]="The wilds whisper to those who know how to listen.",["O"]="Slay 8 Druid of the Moth, 8 Disciple of Lo’sho, 8 Lucid Dream Protector, and 8 Lucid Dream Stalker in the Grove of the Moon, then return to Arch Druid Renethra at Narvalis Point.",["T"]="The Moth’s Heresy"}
T["quests"][42095]={["D"]="If the corruption in the Grove of the Moon spreads further, we will face more than a handful of misguided druids.",["O"]="Speak with Sister Mirallun in the Grove of the Sun on the Isle of Tyrandas.",["T"]="A Dryad’s Counsel"}
T["quests"][42096]={["D"]="The corruption you saw in the Grove of the Moon is only the beginning.",["O"]="Slay 10 Sisters of Rot, 10 Whispering Satyrs, and 5 Rotting Ancients in Elun’aran, then return to Sister Mirallun in the Grove of the Sun.",["T"]="The Rot of Elun’aran"}
T["quests"][42097]={["D"]="The druids behind this corruption do not act alone. Their leader is a keeper of the grove named Krothis.",["O"]="Slay Keeper Krothis in Elun’aran and return to Sister Mirallun.",["T"]="Keeper of the Broken Grove"}
T["quests"][42098]={["D"]="<name>, the Alliance has made great strides in securing grounds on the continent of Kalimdor, all thanks to the Bael Modan Garrison. Our brethren are fighting everyday for their survival, while ensuring our archaelogists can continue their work in excavating the land for crucial artifacts of historical significance!",["O"]="Win a battle in the battle for the Thorn Gorge and report to any of its Battlemasters in your capital cities afterwards.",["T"]="The Thorn Gorge Frontier"}
T["quests"][42099]={["D"]="<name>, the vile and selfish dwarves have infiltrated our holy lands and began desecrating it! In their greed for knowledge they dug deep into the lands of the Earthmother and disrespected her sanctity. We cannot let this stand.",["O"]="Win a battle in the battle for the Thorn Gorge and report to any of its Battlemasters in your capital cities afterwards.",["T"]="The Thorn Gorge Defense"}
T["quests"][42201]={["D"]="*A disarming, friendly voice trickles into your head* You've stuck with the server through its ups and downs.",["O"]="Talk to Ozzy",["T"]="Reclaiming Ozzy"}
T["quests"][42202]={["D"]="*A disarming, friendly voice trickles into your head* Ahhhh it is great to see you again <name>",["O"]="Talk to Ozzy",["T"]="Reclaiming Buccaneer Bubbles"}
T["quests"][42203]={["D"]="*A disarming, friendly voice trickles into your head* You look like you've been through it...",["O"]="Talk to Ozzy",["T"]="Reclaiming D'Dossy"}
T["quests"][42501]={["D"]="We enter into this world alone, and we die alone. Some may find this depressing, but I think it is kind of comforting, don't you?",["O"]="Venture through the world and find yourself.",["T"]="Closure"}
T["quests"][700001]={["D"]="Oink! Oink oink!",["O"]="Bring 1 Raw Black Truffle to the Pig in Elwynn Forest.",["T"]="Oink, Oink!"}
T["units"][1155]="Kelt Thomasin"
T["units"][1156]="Vyrin Swiftwind"
T["units"][2993]="Baine Bloodhoof"
T["units"][3057]="Cairne Bloodhoof"
T["units"][3936]="Shandris Feathermoon"
T["units"][4046]="Magatha Grimtotem"
T["units"][4606]="Aelthalyste"
T["units"][5384]="Brohann Caskbelly"
T["units"][7406]="Oglethorpe Obnoticus"
T["units"][7999]="Tyrande Whisperwind"
T["units"][8125]="Dirge Quikcleave"
T["units"][10537]="Cliffwatcher Longhorn"
T["units"][10599]="Hulfnar Stonetotem"
T["units"][11833]="Rahauro"
T["units"][12042]="Loganaar"
T["units"][12919]="Nat Pagle"
T["units"][13278]="Duke Hydraxis"
T["units"][14463]="Daio the Decrepit"
T["units"][15481]="Spirit of Azuregos"
T["units"][16134]="Rimblat Earthshatter"
T["units"][29479]="Elder Moonhoof"
T["units"][50070]="Rufus Hardwick"
T["units"][60541]="Tonlok"
T["units"][61111]="Pumpworker Zalwan"
T["units"][61803]="Astalor Sunsworn"
T["units"][61840]="Shandlar Thethis"
T["units"][62195]="Razorgust"
T["units"][62416]="Tarwegg Dustbrow"
T["units"][62795]="Raghol"
T["units"][62797]="Grakk Windtamer"
T["units"][62813]="Miraxx Foulheart"
T["units"][62834]="Malgan Windhorn"
T["units"][62836]="Sagh"
T["units"][62839]="Brolan Windhorn"
T["units"][62842]="Nuhlgahn Windhorn"
T["units"][62899]="Olgra"
T["units"][62900]="Arch Druid Renethra Moonwater"
T["units"][62901]="Sentinel Commander Silverstreak"
T["units"][62902]="Zarazar Sagewind"
T["units"][62904]="Irea Dawncaller"
T["units"][62906]="Elendon Truebough"
T["units"][62907]="Talanis Amberscribe"
T["units"][62913]="Grovetender Sellais"
T["units"][62914]="Sister Mirallun"
T["units"][62917]="Keeper Bandalar"
T["units"][62972]="Dhela"
T["units"][62973]="Fisher Rainstrider"
T["units"][62976]="Mhulf Nighthorn"
T["units"][62977]="Moonhoof the Younger"
T["units"][62978]="Shanni Silkhoof"
T["units"][62983]="Thobias Shallowgrave"
T["units"][62984]="Yagoh Riverhorn"
T["units"][63054]="Duln Ashtotem"
T["units"][63056]="Ulf Stonetotem"
T["units"][63059]="Luhal Tannedhorn"
T["units"][63067]="Zandaxxius"
T["units"][63078]="Kralt the Forgotten"
T["units"][63083]="Elder Starstrider"
T["units"][63086]="Erna"
T["units"][63087]="Torgan the Wise"
T["units"][63094]="Bulrok Cloudhoof"
T["units"][63095]="Gordnak"
T["units"][63096]="Nuhlok Starstrider"
T["units"][63098]="Artahla Starstrider"
T["units"][63099]="Pargan Starstrider"
T["units"][63118]="Brave Wildheart"
T["units"][63119]="Andanil Sunsworn"
T["units"][63121]="Tesania Shadewind"
T["units"][63122]="Rhys Dawnbreeze"
T["units"][63127]="Arcanist Cerulon"
T["units"][63160]="Sentinel Velaya"
T["units"][63163]="Groundstender Rainhorn"
T["units"][63168]="Mountaineer Granitebeard"
T["units"][63182]="Archaeologist Evenpike"
T["units"][63183]="Keeper N’las"
T["units"][63189]="Supply Officer Mortimus"
T["units"][63190]="Ranix Crackbolt"
T["units"][63198]="Gor'dush Jawtaker"
T["units"][63201]="Ireth Moondancer"
T["units"][63203]="Fanwyn Wildbrand"
T["units"][63208]="Esoch Steelweaver"
T["units"][900200]="Pig"
T["units"][2510002]="Ozzy"
T["units"][2510040]="Mirelle Ashmoor"
T["objects"][179703]="Cache of the Firelord"
T["objects"][2020312]="WANTED!"
T["items"][42178]="Rite of Resurrection"
T["items"][42180]="Twisting Rift Crystal"
T["items"][42206]="Windtorn Crest Stone"
T["items"][42222]="Crate with Red Crystals"
T["items"][42385]="Half-Burnt Scroll"
